version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
        environment:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: youmise
          DB_DATABASE: circle_test
      # - image: candicexyh/youmise_node_mysql:0.0.1
      - image: circleci/mysql:5.7.21
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_ROOT_PASSWORD: youmise
          MYSQL_ROOT_HOST: "%"
    steps:
      - checkout
      - run: sudo apt-get install -y mysql-client
      - run:
          name: install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.0
      - run:
          name: wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: mysql db
          command: mysql -h localhost -u root -e "create database mate;"
          mysql -h$DB_HOST -u$DB_USERNAME -p$DB_PASSWORD $DB_DATABASE
      - run:
          name: Test
          command: |
            yarn
            yarn test


  # deploy_uat:
  #   docker:
  #     - image: circleci/node:8.9.4-stretch-browsers
  #   steps:
  #     - checkout
  #
  #     - run:
  #         name: Install deployment dependencies
  #         command: |
  #           sudo apt-get -y -qq update
  #           sudo apt-get install python-pip python-dev build-essential
  #           sudo pip install awsebcli --upgrade
  #     - run:
  #         name: Build front end
  #         command: |
  #           cd umise
  #           yarn
  #           yarn build --mode uat
  #           cd ..
  #     - run:
  #         name: Deploying
  #         command: eb deploy

  deploy_dev:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: Build front end
          command: |
            cd umise
            yarn
            yarn build --mode development
            cd ..

      - run: ls umise/dist

      - run:
          name: Deploying
          command: eb deploy

  deploy_prod:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: Build front end
          command: |
            cd umise
            yarn
            yarn build --mode production
            cd ..
      - run:
          name: Deploying
          command: eb deploy $PRODENV


workflows:
  version: 2
  dev_uat_prod:
    jobs:
      - test

      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - test

      # - deploy_uat:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - test
      #
      # - hold:
      #     type: approval
      #     requires:
      #       - deploy_uat
      #
      # - deploy_prod:
      #     requires:
      #       - hold

      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - test
