      # run tests!
      # - run: yarn test
      # - install_gcloud
      #     curl -sSL https://sdk.cloud.google.com | bash

version: 2
jobs:
  build for uat:
    docker:
      - image: candicexyh/youmise-primary:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          # - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: candicexyh/youmise-primary:0.0.1
    steps:
      - checkout
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: gcloud --quiet components update
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud config set project $GCLOUD_PROJECT
      - run: gcloud app deploy app.yaml
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build for uat
      - deploy:
          requires:
            - build for uat
