version: 2
jobs:

  test:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Test connection to database
          command: |
            yarn install
            yarn test-unit


  deploy_uat:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout

      - run:
          name: Install deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploying
          command: eb deploy

  deploy_dev:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: Build front end
          command: |
            cd umise
            npm install
            npm run build
            cd ..

      - run: ls umise/dist

      - run:
          name: Deploying
          command: eb deploy

  deploy_prod:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploying
          command: eb deploy $PRODENV

workflows:
  version: 2
  dev_uat_prod:
    jobs:
      - test

      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - test

      - deploy_uat:
          filters:
            branches:
              only: master
          requires:
            - test

      - hold:
          type: approval
          requires:
            - deploy_uat

      - deploy_prod:
          requires:
            - hold
