version: 2
jobs:
  # build:
  #   docker:
  #     - image: circleci/node:8.9.4-stretch-browsers
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         # fallback to using the latest cache if no exact match is found
  #         # - v1-dependencies-
  #
  #     - run: yarn install
  #
  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: yarn test


  deploy_uat:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install awsebcli --upgrade
      - run: eb deploy --profile default $UATENV

  deploy_dev:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install awsebcli --upgrade
      - run: eb deploy --profile default $DEVENV

  deploy_prod:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install awsebcli --upgrade
      - run: eb deploy --profile default $PRODENV

workflows:
  version: 2
  dev_uat_prod:
    jobs:

      - test

      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - test

      - deploy_uat:
          filters:
            branches:
              only: master
          requires:
            - test

      - hold:
          type: approval
          requires:
            - deploy_uat

      - deploy_prod:
          requires:
            - hold
