// User mutations
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_PASS_CHALLENGE_NEEDED = 'USER_LOGIN_PASS_CHALLENGE_NEEDED';
export const USER_LOGIN_PASS_CHALLENGE_REQUEST = 'USER_LOGIN_PASS_CHALLENGE_REQUEST';
export const USER_LOGIN_PASS_CHALLENGE_SUCCESS = 'USER_LOGIN_PASS_CHALLENGE_SUCCESS';
export const USER_LOGIN_PASS_CHALLENGE_FAILURE = 'USER_LOGIN_PASS_CHALLENGE_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
